//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.LOLWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/CheckUserService.asmx/", ConfigurationName="LOLWebservice.CheckUserServiceSoap")]
    public interface CheckUserServiceSoap {
        
        // CODEGEN: 命名空间 http://localhost/CheckUserService.asmx/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CheckUserService.asmx/HelloWorld", ReplyAction="*")]
        View.LOLWebservice.HelloWorldResponse HelloWorld(View.LOLWebservice.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://localhost/CheckUserService.asmx/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CheckUserService.asmx/matching", ReplyAction="*")]
        View.LOLWebservice.matchingResponse matching(View.LOLWebservice.matchingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://localhost/CheckUserService.asmx/", Order=0)]
        public View.LOLWebservice.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(View.LOLWebservice.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://localhost/CheckUserService.asmx/", Order=0)]
        public View.LOLWebservice.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(View.LOLWebservice.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/CheckUserService.asmx/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class matchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="matching", Namespace="http://localhost/CheckUserService.asmx/", Order=0)]
        public View.LOLWebservice.matchingRequestBody Body;
        
        public matchingRequest() {
        }
        
        public matchingRequest(View.LOLWebservice.matchingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/CheckUserService.asmx/")]
    public partial class matchingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public matchingRequestBody() {
        }
        
        public matchingRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class matchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="matchingResponse", Namespace="http://localhost/CheckUserService.asmx/", Order=0)]
        public View.LOLWebservice.matchingResponseBody Body;
        
        public matchingResponse() {
        }
        
        public matchingResponse(View.LOLWebservice.matchingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/CheckUserService.asmx/")]
    public partial class matchingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool matchingResult;
        
        public matchingResponseBody() {
        }
        
        public matchingResponseBody(bool matchingResult) {
            this.matchingResult = matchingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckUserServiceSoapChannel : View.LOLWebservice.CheckUserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckUserServiceSoapClient : System.ServiceModel.ClientBase<View.LOLWebservice.CheckUserServiceSoap>, View.LOLWebservice.CheckUserServiceSoap {
        
        public CheckUserServiceSoapClient() {
        }
        
        public CheckUserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckUserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckUserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckUserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        View.LOLWebservice.HelloWorldResponse View.LOLWebservice.CheckUserServiceSoap.HelloWorld(View.LOLWebservice.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            View.LOLWebservice.HelloWorldRequest inValue = new View.LOLWebservice.HelloWorldRequest();
            inValue.Body = new View.LOLWebservice.HelloWorldRequestBody();
            View.LOLWebservice.HelloWorldResponse retVal = ((View.LOLWebservice.CheckUserServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        View.LOLWebservice.matchingResponse View.LOLWebservice.CheckUserServiceSoap.matching(View.LOLWebservice.matchingRequest request) {
            return base.Channel.matching(request);
        }
        
        public bool matching(string username, string password) {
            View.LOLWebservice.matchingRequest inValue = new View.LOLWebservice.matchingRequest();
            inValue.Body = new View.LOLWebservice.matchingRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            View.LOLWebservice.matchingResponse retVal = ((View.LOLWebservice.CheckUserServiceSoap)(this)).matching(inValue);
            return retVal.Body.matchingResult;
        }
    }
}
